spring.application.name=sb-ecom-v1

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_v1
spring.datasource.username=postgres
spring.datasource.password=cisco@123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

project.image=images/

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.app.jwtSecret=MySuperStrongJwtSecretKeyForSpringBoot2026SecureKey123
spring.app.jwtExpirationMs=86400000
spring.app.jwtCookieName=springBootEcom